load("@io_bazel_rules_scala//scala:scala.bzl", "scala_binary", "scala_library", "scala_test")

scala_library(
    name = "example",
    srcs = ["MyExampleApp.scala"],
    deps = ["//src/main/java/com/animal"],
)
