#!/bin/bash
set -e

TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export REPO_ROOT="$(cd $TOOLS_DIR && cd .. && pwd)"

export BAZELFE_INCLUDE_DAEMON=true


source $REPO_ROOT/build_tools/bazelfe/common.sh
CONFIG_PATH="$REPO_ROOT/build_tools/bazelfe/config"

1>&2 fetch_binary "$BAZEL_RUNNER_LOCAL_PATH" "$BAZEL_RUNNER_URL" "$BAZEL_RUNNER_SHA_URL"
1>&2 fetch_binary "$BUILDOZER_LOCAL_PATH" "$BUILDOZER_URL" "$BUILDOZER_SHA_URL"


RUST_LOG="warn,bazelfe_core::bazel_runner=warn,bazel_runner=warn" exec "$BAZEL_RUNNER_LOCAL_PATH" --config "$CONFIG_PATH" --buildozer-path "$BUILDOZER_LOCAL_PATH" $BAZEL_REAL "$@"
